---
language: python

dist: xenial

python:
- "3.6"
- "3.7"
- 3.8-dev

install: pip install .[test]

script:
- python setup.py check
- check-manifest
- mypy src
- pytest
- behave

sudo: required

after_success: codecov
